Hellowworld: 
	# dotnet new web -o HelloWorld
	docker build -t bhalamish20/dotnethellowworld:1.0 .
	# docker build -t bhalamish20/dotnethellowworld:1.0 .
	docker login -u bhalamish20 -p Hala!23456
	docker push bhalamish20/dotnethellowworld:1.0
	#  helm create hello-world
	#  cd hello-world
helm template hello-world ./hello-world/
/c/sela/20487D/dotnet/HelloWorld
